name: flutter driver

on: 
   push:
      branches:
         - master
   pull_request:
     

jobs:
  drive:
    runs-on: macos-latest
    strategy:
      # When set to true, GitHub cancels all in-progress jobs if any        
      # matrix job fails.
      fail-fast: false
      matrix:
        api-level: [21, 28, 30] # [minSdk, most used, newest] 18 would be minSDK but does not support x86_64
        target: [default] # [default, google_apis]
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        flutter-version: '1.22.5'
    - run: "flutter --version"
    - run: "flutter pub get"
    - run: "flutter build apk --debug"
    - uses: actions/upload-artifact@v1
      with:
        name: apk
        path: build/app/outputs/flutter-apk/app-debug.apk
